"""unset text-index

Revision ID: 593d727030fa
Revises: 63c58e7a2312
Create Date: 2024-01-15 20:46:14.361878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593d727030fa'
down_revision = '63c58e7a2312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_tg_posts_post_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_posts', schema=None) as batch_op:
        batch_op.create_index('ix_tg_posts_post_text', ['post_text'], unique=False)

    # ### end Alembic commands ###
