"""initial commit

Revision ID: 63c58e7a2312
Revises: 
Create Date: 2024-01-15 20:23:09.285212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c58e7a2312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('linked_chat_id', sa.String(length=32), nullable=True),
    sa.Column('linked_chat_link', sa.String(length=32), nullable=True),
    sa.Column('channel_title', sa.String(length=64), nullable=True),
    sa.Column('channel_description', sa.String(length=512), nullable=True),
    sa.Column('channel_username', sa.String(length=64), nullable=True),
    sa.Column('channel_subs_count', sa.Integer(), nullable=True),
    sa.Column('channel_generated_link', sa.String(length=120), nullable=True),
    sa.Column('channel_posts_per_day', sa.Integer(), nullable=True),
    sa.Column('channel_comments_per_post', sa.Integer(), nullable=True),
    sa.Column('channel_views_per_post', sa.Integer(), nullable=True),
    sa.Column('channel_posts_count', sa.Integer(), nullable=True),
    sa.Column('channel_time_delta', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_channels_channel_id'), ['channel_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_channels_channel_title'), ['channel_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_channels_channel_username'), ['channel_username'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_channels_last_update'), ['last_update'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_channels_linked_chat_id'), ['linked_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_channels_linked_chat_link'), ['linked_chat_link'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_channels_time_create'), ['time_create'], unique=False)

    op.create_table('tg_file_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('road_to_file', sa.String(length=128), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_file_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_file_archive_file_hash'), ['file_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_file_archive_road_to_file'), ['road_to_file'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_file_archive_time_create'), ['time_create'], unique=False)

    op.create_table('tg_media_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediaType_title', sa.String(length=32), nullable=True),
    sa.Column('mediaType_settings', sa.String(length=128), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_media_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_media_types_mediaType_settings'), ['mediaType_settings'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_media_types_mediaType_title'), ['mediaType_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_tg_media_types_time_create'), ['time_create'], unique=False)

    op.create_table('tg_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_firstname', sa.String(length=128), nullable=True),
    sa.Column('user_lastname', sa.String(length=128), nullable=True),
    sa.Column('user_username', sa.String(length=128), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_users_time_create'), ['time_create'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_users_user_id'), ['user_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('tg_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('post_media_type_id', sa.Integer(), nullable=True),
    sa.Column('post_file_id', sa.Integer(), nullable=True),
    sa.Column('post_likes', sa.String(length=256), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('post_likes_count', sa.Integer(), nullable=True),
    sa.Column('post_views', sa.Integer(), nullable=True),
    sa.Column('post_replies', sa.Integer(), nullable=True),
    sa.Column('post_is_parsed', sa.Boolean(), nullable=True),
    sa.Column('post_hours_diff', sa.Float(), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.channel_id'], ),
    sa.ForeignKeyConstraint(['post_file_id'], ['tg_file_archive.id'], ),
    sa.ForeignKeyConstraint(['post_media_type_id'], ['tg_media_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_posts_post_date'), ['post_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_posts_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_posts_post_text'), ['post_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_posts_time_create'), ['time_create'], unique=False)

    op.create_table('tg_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=32), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('comment_linked_channel_id', sa.String(length=32), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.Column('comment_media_type_id', sa.Integer(), nullable=True),
    sa.Column('comment_file_id', sa.Integer(), nullable=True),
    sa.Column('comment_likes', sa.String(length=256), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_link', sa.String(length=128), nullable=True),
    sa.Column('comment_likes_count', sa.Integer(), nullable=True),
    sa.Column('comment_is_posted', sa.Boolean(), nullable=True),
    sa.Column('comment_poster_display', sa.String(length=128), nullable=True),
    sa.Column('comment_poster_id', sa.String(length=32), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.channel_id'], ),
    sa.ForeignKeyConstraint(['comment_file_id'], ['tg_file_archive.id'], ),
    sa.ForeignKeyConstraint(['comment_media_type_id'], ['tg_media_types.id'], ),
    sa.ForeignKeyConstraint(['comment_poster_id'], ['tg_users.user_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['tg_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_comments_comment_date'), ['comment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_comments_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_comments_comment_likes'), ['comment_likes'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_comments_comment_text'), ['comment_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_comments_time_create'), ['time_create'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_comments_time_create'))
        batch_op.drop_index(batch_op.f('ix_tg_comments_comment_text'))
        batch_op.drop_index(batch_op.f('ix_tg_comments_comment_likes'))
        batch_op.drop_index(batch_op.f('ix_tg_comments_comment_id'))
        batch_op.drop_index(batch_op.f('ix_tg_comments_comment_date'))

    op.drop_table('tg_comments')
    with op.batch_alter_table('tg_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_posts_time_create'))
        batch_op.drop_index(batch_op.f('ix_tg_posts_post_text'))
        batch_op.drop_index(batch_op.f('ix_tg_posts_post_id'))
        batch_op.drop_index(batch_op.f('ix_tg_posts_post_date'))

    op.drop_table('tg_posts')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_tg_users_time_create'))

    op.drop_table('tg_users')
    with op.batch_alter_table('tg_media_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_media_types_time_create'))
        batch_op.drop_index(batch_op.f('ix_tg_media_types_mediaType_title'))
        batch_op.drop_index(batch_op.f('ix_tg_media_types_mediaType_settings'))

    op.drop_table('tg_media_types')
    with op.batch_alter_table('tg_file_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_file_archive_time_create'))
        batch_op.drop_index(batch_op.f('ix_tg_file_archive_road_to_file'))
        batch_op.drop_index(batch_op.f('ix_tg_file_archive_file_hash'))

    op.drop_table('tg_file_archive')
    with op.batch_alter_table('tg_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_channels_time_create'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_linked_chat_link'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_linked_chat_id'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_last_update'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_channel_username'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_channel_title'))
        batch_op.drop_index(batch_op.f('ix_tg_channels_channel_id'))

    op.drop_table('tg_channels')
    # ### end Alembic commands ###
